mcq_test/urls.py
from django.urls import path
from . import views 

app_name='mcq_test'
urlpatterns = [
    path('', views.login_view, name='login_view'), 
    path('logout/', views.logout_view, name='logout'), 
    path('faculty/', views.dashboard_faculty, name='dashboard_faculty'),
    path('faculty/test/<int:tid>/', views.display_test_faculty, name='display_test_faculty'),
    path('test/leaderboard/<int:tid>/', views.leaderboard, name='leaderboard'),
    path('student/', views.dashboard_student, name='dashboard_student'),
    path('create/name/', views.create_test_page1, name='create_test_page1'), 
    path('create/ques/<int:tid>/', views.create_test_page2, name='create_test_page2'), 
    path('create/link/<int:tid>/', views.generate_test_link, name='generate_test_link'), 
    path('test/<str:test_id>/', views.test_view, name='test_view'), 
    # path('display/', views.display_test, name='display_test'), 
]

test_GAC/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mcq_test.urls')),
]

mcq_test/models.py
from django.db import models
from django.contrib.auth.models import User

# # Create your models here.
# class Test(models.Model):
#     id = models.AutoField(primary_key=True)
#     # question =  models.ManyToManyField(Question, blank=False, related_name="")
#     activationTime = models.DateTimeField
#     # link = models.CharField(blank=False) Generate it

#     def __str__(self):
#         pass
class Users(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_student = models.BooleanField(default=False)
    is_faculty = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user.username)

class Test(models.Model):
    user = models.ForeignKey("Users", on_delete=models.CASCADE)
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    start_date = models.DateField()
    start_time = models.TimeField()
    duration = models.DurationField()

    def __str__(self):
        return str(self.id) + " " + self.name

class Question(models.Model):
    # question_id = models.AutoField(primary_key=True)
    test = models.ForeignKey("Test", related_name="questions", on_delete=models.CASCADE)
    question = models.CharField(max_length=500)

    def __str__(self):
        return str(self.test) + " - " + str(self.question)

class Choice(models.Model):
    choice_id = models.AutoField(primary_key=True)
    question = models.ForeignKey("Question", related_name="choices", on_delete=models.CASCADE)
    choice = models.CharField(max_length=50)
    answer = models.BooleanField(default=False)

    def __str__(self):
        return str(self.question) + " - " +str(self.choice_id)

class Marks(models.Model):
    id = models.AutoField(primary_key=True)
    test = models.ForeignKey('Test', on_delete=models.CASCADE)
    student = models.ForeignKey('Users', on_delete=models.CASCADE)
    marks = models.IntegerField(default=0)
    
    def __str__(self):
        return str(self.test_id) + '-' + str(self.student) + '-' + str(self.marks)

mcq_test/forms.py
from django import forms
from .models import Test, Question, Choice

class TestCreateNameForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = ('name','start_date', 'start_time', 'duration',)

class TestCreateQuestionForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(TestCreateQuestionForm, self).__init__(*args, **kwargs)
    
    class Meta:
        model = Question
        fields = ('question',)

class TestCreateChoiceForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(TestCreateChoiceForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Choice
        fields = ('choice', 'answer',)

mcq_test/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import login, logout, authenticate
from django.utils import timezone
from .forms import TestCreateNameForm, TestCreateQuestionForm, TestCreateChoiceForm
from .models import Test, Users, User, Question, Choice, Marks
from datetime import datetime, date, time, timedelta
import base64
# Create your views here.

def login_view(request):
    if request.user.is_authenticated:
        users = Users.objects.filter(user=request.user)
        if not users:
            return redirect('mcq_test:logout')
        else:
            user=users[0]
            if user.is_student:
                return redirect('mcq_test:dashboard_student')
            if user.is_faculty:
                return redirect('mcq_test:dashboard_faculty')
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        userObject = User.objects.filter(username=username)
        userObject = authenticate(username=username, password=password)
        if userObject:
            login(request, userObject)
            user = Users.objects.filter(user=userObject)
            if user and user[0].is_faculty:
                return redirect('mcq_test:dashboard_faculty')

            elif user and user[0].is_student:
                return redirect('mcq_test:dashboard_student')
                
            else:
                return render(request, 'mcq_test/login.html', {'i': 'Invalid ID/Password'})
        else:
                return render(request, 'mcq_test/login.html', {'i': 'Invalid ID/Password'})
    else:
        return render(request,'mcq_test/login.html')

def logout_view(request):
    logout(request)
    return redirect("/")

def create_test_page1(request) :
    # print(request.user.is_faculty)
    user = Users.objects.filter(user=request.user)[0]
    if request.user.is_authenticated and user.is_faculty:
        if request.method == "POST" :
            form = TestCreateNameForm(request.POST) #, user=request.user)
            if form.is_valid():
                test = form.save(commit=False)
                # test.author = request.user
                # test.published_date = timezone.now()
                test.name = request.POST.get('name')
                start_date = request.POST.get('start_date')
                test.start_date = date(year=int(start_date[0:4]), month=int(start_date[5:7]), day=int(start_date[8:10]))
                start_time = request.POST.get('start_time')
                test.start_time = time(hour=int(start_time[0:2]), minute=int(start_time[3:5]), second=int(start_time[6:8]))
                duration = request.POST.get('duration')
                test.duration = timedelta(days=0, hours=int(duration[0:2]), minutes=int(duration[3:5]), seconds=(int(duration[6:8])))
                test.user = user
                test.save()
                return redirect('mcq_test:create_test_page2', tid=test.id)
            else:
                form = TestCreateNameForm()
                return render(request, 'mcq_test/create_test_page1.html', {'form': form, 'error': 'error'})
        else:
            form = TestCreateNameForm()
            return render(request, 'mcq_test/create_test_page1.html', {'form': form})
    else:
        return redirect('mcq_test:login_view')

def create_test_page2(request, tid) :
    # if request.user.is_authenticated() and request.user.is_faculty:
    test = get_object_or_404(Test, id=tid)
    if request.method == "POST" :
        form1 = TestCreateQuestionForm(request.POST, prefix="q") #, user=request.user)
        form2 = TestCreateChoiceForm(request.POST, prefix="c1") #, user=request.user)
        form3 = TestCreateChoiceForm(request.POST, prefix="c2") #, user=request.user)
        form4 = TestCreateChoiceForm(request.POST, prefix="c3") #, user=request.user)
        form5 = TestCreateChoiceForm(request.POST, prefix="c4") #, user=request.user)
        if form1.is_valid() and form2.is_valid() and form3.is_valid() and form4.is_valid() and form5.is_valid():
            question = form1.save(commit=False)
            question.test = test
            question.question = form1.cleaned_data['question']
            question.save()
        #     question = get_object_or_404()
            choice1 = form2.save(commit=False)
            choice1.question = question
            choice1.choice = form2.cleaned_data['choice']
            choice1.answer = form2.cleaned_data['answer']
            choice1.save()
            choice2 = form3.save(commit=False)
            choice2.question = question
            choice2.choice = form3.cleaned_data['choice']
            choice2.answer = form3.cleaned_data['answer']
            choice2.save()
            choice3 = form4.save(commit=False)
            choice3.question = question
            choice3.choice = form4.cleaned_data['choice']
            choice3.answer = form4.cleaned_data['answer']
            choice3.save()
            choice4 = form5.save(commit=False)
            choice4.question = question
            choice4.choice = form5.cleaned_data['choice']
            choice4.answer = form5.cleaned_data['answer']
            choice4.save()
            
            if request.POST.get("next"):
                return redirect('mcq_test:create_test_page2', tid=test.id)
            elif request.POST.get("submit"):
                return redirect('mcq_test:generate_test_link', tid=test.id)                
    else:
        form1 = TestCreateQuestionForm(prefix="q")
        form2 = TestCreateChoiceForm(prefix="c1")
        form3 = TestCreateChoiceForm(prefix="c2")
        form4 = TestCreateChoiceForm(prefix="c3")
        form5 = TestCreateChoiceForm(prefix="c4")
        return render(request, 'mcq_test/create_test_page2.html', {'form1': form1, 'form2':form2, 'form3': form3, 'form4':form4, 'form5': form5, 'tid':tid})

def generate_test_link(request, tid):
    link = "http://127.0.0.1:8000/test/" + (base64.b64encode(str(tid).encode('utf-8'))).decode('utf-8')
    return render(request, 'mcq_test/generate_test_link.html', {'link': link})

def display_test_faculty(request, tid):
    user = Users.objects.filter(user=request.user)[0]
    tests = Test.objects.filter(user=user)
    if request.user.is_authenticated and user.is_faculty and tests:
        test = Test.objects.filter(id=tid)[0]
        questions = Question.objects.filter(test=test)
        choices=Choice.objects.none()
        for question in questions:
            choices = choices | Choice.objects.filter(question=question)
        return render(request, 'mcq_test/display_test_faculty.html', {'test':test, 'questions':questions, 'choices':choices})
    else:
        return redirect('mcq_test:login_view')

    

def dashboard_faculty(request):
    user = Users.objects.filter(user=request.user)[0]
    if request.user.is_authenticated and user.is_faculty:
        tests = Test.objects.filter(user=user)
        return render(request, 'mcq_test/dashboard_faculty.html', {'tests': tests, 'username':request.user.username})
    else:
        return redirect('mcq_test:login_view')

def dashboard_student(request):
    user = Users.objects.filter(user=request.user)[0]
    if request.user.is_authenticated and user.is_student:
        marks = Marks.objects.filter(student=user)
        tests = Test.objects.none()
        for mark in marks:
            tests = tests | Test.objects.filter(id=mark.test.id)
        return render(request, 'mcq_test/dashboard_student.html', {'tests': tests, 'marks': marks, 'username':request.user.username})
    else:
        return redirect('mcq_test:login_view')

def leaderboard(request, tid):
    if request.user.is_authenticated:
        test = Test.objects.filter(id=tid)[0]
        marks = Marks.objects.filter(test=test)
        return render(request, 'mcq_test/leaderboard.html', {'marks': marks, 'tid':test.id})
    else:
        return redirect('mcq_test:login_view')

def test_view(request, test_id):
    if request.user.is_authenticated:
        user=Users.objects.filter(user=request.user)[0]
        if user.is_student:
            #Add specific user condition here
            if request.method == "POST":
                tid = int(base64.b64decode(test_id).decode('utf-8'))
                test = Test.objects.filter(id=tid)[0]
                questions = Question.objects.filter(test=test)
                marks = Marks.objects.filter(student=user, test=test)
                if marks:
                    return HttpResponse("Can't Submit as You have already taken this test...")
                else:
                    answers = {}
                    answers_selected = {}

                    for question in questions:
                        temp = []
                        for choice in list(Choice.objects.filter(question=question, answer=True)):
                            temp.append(str(choice.choice_id))
                        
                        answers[question.question] = temp

                    for question in questions:
                        answers_selected[question.question] = request.POST.getlist(question.question)
                    
                    marks = 0
                    for question in questions:
                        base = answers[question.question]
                        check = answers_selected[question.question]
                        if base == check:
                            marks+=1
                    marks_object = Marks()
                    marks_object.test = test
                    marks_object.student = user
                    marks_object.marks = marks
                    marks_object.save()
                    return HttpResponse('Thanks...' + str(marks))
            else:
                tid = int(base64.b64decode(test_id).decode('utf-8'))
                test = Test.objects.filter(id=tid)[0]

mcq_test/templates/mcq_test/create_test_page1.html
<HTML>
    <body>
        <h1> SAGAR1</h1>
        {% if error %}
            <p>INVALID INFO</p>
        {% endif %}
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Next</button>
        </form>
    </body>
</HTML>

mcq_test/templates/mcq_test/create_test_page2.html
<HTML>
    <body>
        <h1> SAGAR2</h1>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form1.as_p }}
            {{ form2.as_p }}
            {{ form3.as_p }}
            {{ form4.as_p }}
            {{ form5.as_p }}
            <button type="submit" class="save btn btn-default" name="next" value="next">Add Question</button>
            <button type="submit" class="save btn btn-default" name="submit" value="next">Submit Test</button>
        </form>
    </body>
</HTML>

mcq_test/templates/mcq_test/dashboard_faculty.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="{% static 'dashboard_faculty/img/favicon.ico' %}">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Faculty Dashboard</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="{% static 'dashboard_faculty/css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{% static 'dashboard_faculty/css/animate.min.css' %}" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="{% static 'dashboard_faculty/css/light-bootstrap-dashboard.css' %}" rel="stylesheet"/>

    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="{% static 'dashboard_faculty/css/pe-icon-7-stroke.css' %}" rel="stylesheet" />

</head>
<body>

<div class="wrapper">
    <div class="sidebar" data-color="black" data-image="{% static 'dashboard_faculty/img/sidebar-5.jpg' %}">

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="" class="simple-text">
                    {{ username }}
                </a>
            </div>

            <ul class="nav">
                <li class="active">
                    <a href="">
                        <i class="pe-7s-graph"></i>
                        <p>Dashboard</p>
                </li>
                <li>
                    <a href="{% url 'mcq_test:create_test_page1' %}">
                        <i class="pe-7s-note2"></i>
                        <p>Create Test</p>
                    </a>
                </li>
                
            </ul>
    	</div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="">Dashboard</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-dashboard"></i>
								<p class="hidden-lg hidden-md">Dashboard</p>
                            </a>
                        </li>
                        
                    </ul>

                    <ul class="nav navbar-nav navbar-right">

                        <li>
                            <a href="{% url 'mcq_test:logout' %}">
                                <p>Log out</p>
                            </a>
                        </li>
						<li class="separator hidden-lg"></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-4">
                            {% for test in tests %}
                            <div class="card">
                                    <h3><a href="{% url 'mcq_test:display_test_faculty' tid=test.id%}">{{ test.name }}</a><br/></h3>
                                    <div class="stats">
                                            <i class="fa fa-clock-o"></i> <a href="{% url 'mcq_test:leaderboard' tid=test.id%}">leaderboard</a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>

        <footer class="footer">
            <div class="container-fluid">
                <p class="copyright pull-right">
                    &copy; <script>document.write(new Date().getFullYear())</script> Made with love for a better web
                </p>
            </div>
        </footer>

    </div>
</div>


</body>

    <!--   Core JS Files   -->
    <script src="{% static 'dashboard_faculty/js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'dashboard_faculty/js/bootstrap.min.js' %}" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="{% static 'dashboard_faculty/js/chartist.min.js' %}"></script>

    <!--  Notifications Plugin    -->
    <script src="{% static 'dashboard_faculty/js/bootstrap-notify.js' %}"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
	<script src="{% static 'dashboard_faculty/js/light-bootstrap-dashboard.js' %}"></script>

	<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
	<script src="{% static 'dashboard_faculty/js/demo.js' %}"></script>

</html>

mcq_test/templates/mcq_test/dashboard_faculty2.html
<HTML>
    <body>
        <h1> Faculty DASHBOARD</h1>
        {% for test in tests %}
            <h3><a href="{% url 'mcq_test:display_test_faculty' tid=test.id%}">{{ test.name }}</a><br/></h3>
            <h4><a href="{% url 'mcq_test:leaderboard' tid=test.id%}">leaderboard</a><br/></h4>
        {% endfor %}
    </body>
</HTML>

mcq_test/templates/mcq_test/dashboard_student.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="{% static 'dashboard_faculty/img/favicon.ico' %}">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Student Dashboard</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="{% static 'dashboard_faculty/css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{% static 'dashboard_faculty/css/animate.min.css' %}" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="{% static 'dashboard_faculty/css/light-bootstrap-dashboard.css' %}" rel="stylesheet"/>

    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="{% static 'dashboard_faculty/css/pe-icon-7-stroke.css' %}" rel="stylesheet" />

</head>
<body>

<div class="wrapper">
    <div class="sidebar" data-color="black" data-image="{% static 'dashboard_faculty/img/sidebar-5.jpg' %}">

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="" class="simple-text">
                    {{ username }}
                </a>
            </div>

            <ul class="nav">
                <li class="active">
                    <a href="">
                        <i class="pe-7s-graph"></i>
                        <p>Dashboard</p>
                </li>
            </ul>
    	</div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="">Dashboard</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-dashboard"></i>
								<p class="hidden-lg hidden-md">Dashboard</p>
                            </a>
                        </li>
                        
                    </ul>

                    <ul class="nav navbar-nav navbar-right">

                        <li>
                            <a href="{% url 'mcq_test:logout' %}">
                                <p>Log out</p>
                            </a>
                        </li>
						<li class="separator hidden-lg"></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-4">
                            {% for test in tests %}
                            <div class="card">
                                    <h3>{{ test.name }}<br/></h3>
                                    <div class="stats">
                                            <i class="fa fa-clock-o"></i> <a href="{% url 'mcq_test:leaderboard' tid=test.id%}">leaderboard</a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>

        <footer class="footer">
            <div class="container-fluid">
                <p class="copyright pull-right">
                    &copy; <script>document.write(new Date().getFullYear())</script> Made with love for a better web
                </p>
            </div>
        </footer>

    </div>
</div>


</body>

    <!--   Core JS Files   -->
    <script src="{% static 'dashboard_faculty/js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'dashboard_faculty/js/bootstrap.min.js' %}" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="{% static 'dashboard_faculty/js/chartist.min.js' %}"></script>

    <!--  Notifications Plugin    -->
    <script src="{% static 'dashboard_faculty/js/bootstrap-notify.js' %}"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
	<script src="{% static 'dashboard_faculty/js/light-bootstrap-dashboard.js' %}"></script>

	<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
	<script src="{% static 'dashboard_faculty/js/demo.js' %}"></script>

</html>

mcq_test/templates/mcq_test/dashboard_student2.html
<HTML>
    <body>
        <h1> Student DASHBOARD</h1>
        {% for test in tests %}
            <h3>{{ test.name }} - <br/></h3>
            <h4><a href="{% url 'mcq_test:leaderboard' tid=test.id%}">leaderboard</a><br/></h4>
        {% endfor %}
    </body>
</HTML>

mcq_test/templates/mcq_test/display_test_faculty.html
<HTML>
    <body>
        <h1> {{ test.name }}</h1><br/>
        <h2> {{ test.start_date }}</h2><br/>
        <h2> {{ test.start_time }}</h2><br/>
        <h2> {{ test.duration }}</h2><br/>
        <br/>
        {% for question in questions %}
            <h4>{{ question.question }}</h4>
            <br/>
            {% for choice in choices %}
                {% if choice.question == question %}
                    <h6>{{ choice.choice }}</h6>
                    {% if choice.answer %}
                        <h6>ANSWER</h6>
                    {% endif %}
                    <br/>
                {% endif %}
            {% endfor %}
            <br/>
        {% endfor %}
    </body>
</HTML>

mcq_test/templates/mcq_test/generate_test_link.html
<HTML>
    <body>
        <h1> LINK </h1>
        {{ link }}
    </body>
</HTML>

mcq_test/templates/mcq_test/leaderboard.html
<HTML>
    <body>
        <h1> LEADERBOARD</h1><br/><br/>
        <h1> {{ tid }}</h1><br/><br/>
        {% for mark in marks %}
            {{ mark.student.user.username }} - {{ mark.marks }}
            <br/>
        {% endfor %}
    </body>
</HTML>

mcq_test/templates/mcq_test/login2.html
<HTML>
    <body>
        <h1> LOGIN</h1>
        {% if i %}
        <p>Username and Password didn't match.Please try again.</p>
        {% endif %}

        <form method="POST" action="{% url 'mcq_test:login_view' %}">
        {% csrf_token %}
            <input type="text" placeholder="Enter Username" name="username"><br/>
            <input type="password" placeholder="Enter Password" name="password"> <br/>  
            <button type="submit">Login</button>
        </form>
    </body>
</HTML>

mcq_test/templates/mcq_test/test_view.html
<HTML>
    <body>
        <h1> {{ test.name }}</h1><br/>
        <h2> {{ test.start_date }}</h2><br/>
        <h2> {{ test.start_time }}</h2><br/>
        <h2> {{ test.duration }}</h2><br/>
        <br/>
        <form method="POST" class="post-form">{% csrf_token %}
            {% for question in questions %}
                <h4>{{ question.question }}</h4>
                <br/>
                {% for choice in choices %}
                    {% if choice.question == question %}
                    <input type="checkbox" value="{{ choice.choice_id }}" name="{{ question.question }}"><h6> {{ choice.choice }}</h6> </input>
                    <br/>
                    {% endif %}
                {% endfor %}
                <br/>
            {% endfor %}
            <button type="submit" class="save btn btn-default">Next</button>
        </form>
    </body>
</HTML>